# Generated by Django 4.0.6 on 2022-09-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('types', models.CharField(choices=[('Telephone interview', 'Telephone interview'), ('Technical interview', 'Technical interview'), ('Code interview', 'Code interview'), ('Final interview', 'Final interview')], max_length=30)),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.interviewer')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicant')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], default=None, max_length=5)),
                ('rate', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.interviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.interview')),
            ],
        ),
    ]
