# Generated by Django 4.0.6 on 2022-09-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_applicant_uer_type_and_more'),
        ('Interview', '0002_alter_feedback_feedback_alter_feedback_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.applicant'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='types',
            field=models.CharField(choices=[('Telephone Interview', 'Telephone Interview'), ('Technical Interview', 'Technical Interview'), ('Code Interview', 'Code Interview'), ('Final Interview', 'Final Interview')], default='Telephone Interview', max_length=30),
        ),
        migrations.DeleteModel(
            name='InterviewApplication',
        ),
    ]
