# Generated by Django 4.0.6 on 2022-09-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0009_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
