# Generated by Django 4.0.6 on 2022-09-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0011_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
    ]
