# Generated by Django 4.0.6 on 2022-09-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='uer_type',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='uer_type',
            field=models.IntegerField(default=2),
        ),
    ]
