# Generated by Django 4.0.6 on 2022-09-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicant_uer_type_interviewer_uer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='uer_type',
        ),
    ]
