# Generated by Django 4.0.6 on 2022-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_applicant_uer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='uer_type',
            field=models.CharField(choices=[(1, 'HR'), (2, 'interviewer'), (3, 'applicant')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='uer_type',
            field=models.CharField(choices=[(1, 'HR'), (2, 'interviewer'), (3, 'applicant')], default=2, max_length=1),
        ),
    ]
