# Generated by Django 4.0.6 on 2022-09-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_applicant_uer_type_interviewer_uer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='uer_type',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='uer_type',
        ),
    ]
